<a href="https://colab.research.google.com/github/Clestialcosmos/Data_Visualisation/blob/main/DV2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("/content/student_details_batch1.csv")
df2 = pd.read_csv("/content/student_details_batch2.csv")

In [3]:
df_master_details = pd.concat([df1, df2],axis=0)

In [4]:
df_master_details.head()

,StudentID,Age,Monthly_Allowance,Department,Hostel_Status,Study_Hours
0,GLA0001,21.0,7543.397708,Computer Science,NaN,26.8
1,GLA0002,20.0,5540.686576,Mechanical,NaN,35.2
2,GLA0003,NaN,4081.932081,Electrical,Day Scholar,38.2
3,GLA0004,22.0,1263.675179,Civil,Hosteller,10.1
4,GLA0005,20.0,1528.882644,NaN,Day Scholar,37.4

In [5]:
print(df1.shape)
print(df2.shape)
print(df_master_details.shape)

(100, 6)
(50, 6)
(150, 6)

In [6]:
df_master_details['Age'] = df_master_details['Age'].fillna(df_master_details['Age'].mean())

In [7]:
df_master_details['Monthly_Allowance'] = df_master_details['Monthly_Allowance'].fillna(df_master_details['Monthly_Allowance'].median())

In [8]:
df_master_details['Department'] = df_master_details['Department'].fillna(df_master_details['Department'].mode()[0])

In [9]:
df_master_details['Hostel_Status'] = df_master_details['Hostel_Status'].fillna("Not Specified")

In [10]:
df_master_details.head()

,StudentID,Age,Monthly_Allowance,Department,Hostel_Status,Study_Hours
0,GLA0001,21.000000,7543.397708,Computer Science,Not Specified,26.8
1,GLA0002,20.000000,5540.686576,Mechanical,Not Specified,35.2
2,GLA0003,19.848485,4081.932081,Electrical,Day Scholar,38.2
3,GLA0004,22.000000,1263.675179,Civil,Hosteller,10.1
4,GLA0005,20.000000,1528.882644,Computer Science,Day Scholar,37.4

In [11]:
from sklearn.impute import KNNImputer

In [12]:
subset_df = df_master_details[['Age', 'Monthly_Allowance','Study_Hours']]

In [13]:
imputer = KNNImputer(n_neighbors=5)

In [14]:
imputed_data= imputer.fit_transform(subset_df)

In [15]:
imputed_df = pd.DataFrame(imputed_data, columns=subset_df.columns)

In [16]:
df_master_details['Study_Hours'] = imputed_df['Study_Hours']

In [17]:
df = pd.read_csv("/content/student_grades.csv")

In [18]:
df_joined = pd.merge(df_master_details, df, on="StudentID", how="inner")

In [20]:
df_joined.shape

(100, 8)

In [22]:
df_left_join = pd.merge(df_master_details, df, on="StudentID", how="left")
df_left_join.shape

(150, 8)

In [24]:
df_left_join.to_csv("final_student_database.csv",index = False)